use crate::diagnostic::Diagnostic;
use crate::hir::{Constructor, LifecycleStep, Module, OwnerKind, TypeKind, TypeRef};
use crate::metadata::stable_class_id;

pub fn emit(abi_identity: &str, module: &Module) -> Result<String, Vec<Diagnostic>> {
    validate_backend_plans(module)?;
    let mut output = String::new();
    output.push_str("// @generated by rustpp; do not edit.\n");
    output.push_str(&format!(
        "// ABI identity: {}\n\n",
        abi_identity.replace('\n', " ")
    ));

    for class in &module.value_classes {
        output.push_str(&format!(
            "#[allow(dead_code)]\npub struct {}{} {} {{\n",
            class.name, class.generics.declaration, class.generics.where_clause
        ));
        for field in &class.fields {
            if field.public {
                output.push_str("pub ");
            }
            output.push_str(&format!(
                "{}: {},\n",
                field.name,
                backend_type(module, &field.ty)
            ));
        }
        output.push_str("}\n");
        output.push_str(&format!(
            "impl{} {}{} {} {{\n",
            class.generics.impl_params,
            class.name,
            class.generics.type_args,
            class.generics.where_clause
        ));
        output.push_str("pub fn new(");
        for (index, param) in class.constructor.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&format!(
                "{}: {}",
                param.name,
                backend_type(module, &param.ty)
            ));
        }
        output.push_str(") -> Self { Self {\n");
        for initializer in &class.constructor.initializers {
            output.push_str(&initializer.field);
            if let Some(expression) = &initializer.expression {
                output.push_str(": ");
                output.push_str(expression);
            }
            output.push_str(",\n");
        }
        output.push_str("} }\n");
        for method in &class.methods {
            if method.public {
                output.push_str("pub ");
            }
            output.push_str(&backend_method_signature(module, &method.signature));
            output.push_str(" {\n");
            output.push_str(method.body.as_deref().unwrap_or_default());
            output.push_str("\n}\n");
        }
        output.push_str("}\n");
        if let Some(body) = &class.drop_body {
            output.push_str(&format!(
                "impl{} Drop for {}{} {} {{ fn drop(&mut self) {{\n{body}\n}} }}\n",
                class.generics.impl_params,
                class.name,
                class.generics.type_args,
                class.generics.where_clause
            ));
        }
    }

    if !module.classes.is_empty() {
        output.push_str(
            "#[doc(hidden)] #[derive(Clone, Copy, PartialEq, Eq)] pub struct __RppClassId(pub u128);\n\
             #[doc(hidden)] pub struct __RppCastEntry {\n\
             target: __RppClassId,\n\
             make_const: unsafe fn(*const (), *mut ()),\n\
             make_mut: unsafe fn(*mut (), *mut ()),\n\
             }\n\
             #[doc(hidden)] pub struct __RppTypeDesc {\n\
             active_class: __RppClassId,\n\
             complete_storage_class: __RppClassId,\n\
             casts: &'static [__RppCastEntry],\n\
             }\n\
             impl __RppTypeDesc {\n\
             fn find(&self, target: __RppClassId) -> Option<&__RppCastEntry> { self.casts.iter().find(|entry| entry.target == target) }\n\
             #[doc(hidden)] pub fn active_class_id(&self) -> u128 { self.active_class.0 }\n\
             #[doc(hidden)] pub fn complete_storage_class_id(&self) -> u128 { self.complete_storage_class.0 }\n\
             }\n\
             mod __rpp_runtime_object_sealed { pub trait Sealed {} }\n\
             pub trait RustppObject: __rpp_runtime_object_sealed::Sealed {\n\
             #[doc(hidden)] fn __rpp_complete_address(&self) -> usize;\n\
             #[doc(hidden)] fn __rpp_type_desc(&self) -> &'static __RppTypeDesc;\n\
             }\n",
        );
    }

    for class in &module.classes {
        let data = format!("__{}Data", class.name);
        let storage = format!("__{}Storage", class.name);
        let frame = format!("__{}ActivationFrame", class.name);
        let activation_guard = format!("__{}ActivationGuard", class.name);
        let deactivation_guard = format!("__{}DeactivationGuard", class.name);
        let view = format!("{}View", class.name);
        let box_owner = format!("{}Box", class.name);
        let rc_owner = format!("{}Rc", class.name);
        let arc_owner = format!("{}Arc", class.name);
        let seal_module = format!("__rpp_{}_sealed", class.name.to_lowercase());
        let inline_initializers: Vec<_> = class
            .constructor
            .initializers
            .iter()
            .filter(|initializer| initializer.inline.is_some())
            .collect();
        let has_subobjects = !class.bases.is_empty() || !inline_initializers.is_empty();

        output.push_str(&format!("struct {frame} {{\n"));
        for base in &class.bases {
            let base_class = class_by_id(module, base.class);
            output.push_str(&format!(
                "{}: __{}ActivationFrame,\n",
                base_frame_field(base.class),
                base_class.name
            ));
        }
        for initializer in class
            .constructor
            .initializers
            .iter()
            .filter(|initializer| initializer.inline.is_some())
        {
            let inline = initializer.inline.as_ref().unwrap();
            let child = class_by_id(module, inline.class);
            output.push_str(&format!(
                "__rpp_{}: __{}ActivationFrame,\n",
                initializer.field, child.name
            ));
        }
        for param in &class.activation_params {
            output.push_str(&format!(
                "{}: {},\n",
                param.name,
                backend_type(module, &param.ty)
            ));
        }
        output.push_str("}\n");
        output.push_str(&format!("#[allow(dead_code)]\nstruct {data} {{\n"));
        for field in class.fields.iter().rev() {
            output.push_str(&format!(
                "{}: {},\n",
                field.name,
                backend_type(module, &field.ty)
            ));
        }
        for base in class.bases.iter().rev() {
            let base_class = class_by_id(module, base.class);
            output.push_str(&format!(
                "{}: __{}Data,\n",
                base_data_field(base.class),
                base_class.name
            ));
        }
        output.push_str("}\n");
        if has_subobjects {
            output.push_str(&format!(
                "struct {activation_guard} {{ data: *mut {data}, completed: usize }}\n"
            ));
            output.push_str(&format!("impl Drop for {activation_guard} {{ fn drop(&mut self) {{\n// SAFETY [SC-STAGE-VIEW]: rollback owns the unique final Data borrow and only deactivates successfully completed substages.\nunsafe {{\n"));
            let mut stage_index = class.bases.len() + inline_initializers.len();
            for initializer in inline_initializers.iter().rev() {
                stage_index -= 1;
                output.push_str(&format!(
                    "if self.completed > {stage_index} {{ (*self.data).{}.__rpp_deinit(); }}\n",
                    initializer.field
                ));
            }
            for base in class.bases.iter().rev() {
                stage_index -= 1;
                output.push_str(&format!(
                    "if self.completed > {stage_index} {{ (*self.data).{}.__rpp_deinit(); }}\n",
                    base_data_field(base.class)
                ));
            }
            output.push_str("} } }\n");
            output.push_str(&format!(
                "struct {deactivation_guard} {{ data: *mut {data}, remaining: usize }}\n"
            ));
            output.push_str(&format!("impl Drop for {deactivation_guard} {{ fn drop(&mut self) {{\n// SAFETY [SC-STAGE-VIEW]: unwind cleanup owns the unique complete Data borrow and consumes each remaining deactivation obligation once.\nunsafe {{\n"));
            let mut stage_index = class.bases.len() + inline_initializers.len();
            for initializer in inline_initializers.iter().rev() {
                stage_index -= 1;
                output.push_str(&format!(
                    "if self.remaining > {stage_index} {{ self.remaining = {stage_index}; (*self.data).{}.__rpp_deinit(); }}\n",
                    initializer.field
                ));
            }
            for base in class.bases.iter().rev() {
                stage_index -= 1;
                output.push_str(&format!(
                    "if self.remaining > {stage_index} {{ self.remaining = {stage_index}; (*self.data).{}.__rpp_deinit(); }}\n",
                    base_data_field(base.class)
                ));
            }
            output.push_str("} } }\n");
        }
        output.push_str(&format!("impl {data} {{\n"));
        output.push_str("fn __rpp_new(");
        emit_params(&mut output, module, &class.constructor);
        output.push_str(&format!(") -> (Self, {frame}) {{\n"));
        for base in &class.bases {
            let base_class = class_by_id(module, base.class);
            let initializer = class
                .constructor
                .base_initializers
                .iter()
                .find(|initializer| initializer.class == base.class)
                .expect("validated direct base must have one initializer");
            output.push_str(&format!(
                "let ({}_data, {}_frame) = __{}Data::__rpp_new({});\n",
                base_data_field(base.class),
                base_frame_field(base.class),
                base_class.name,
                initializer.arguments
            ));
        }
        for initializer in &class.constructor.initializers {
            if let Some(inline) = &initializer.inline {
                let child = class_by_id(module, inline.class);
                output.push_str(&format!(
                    "let (__rpp_{}_data, __rpp_{}_frame) = __{}Data::__rpp_new({});\n",
                    initializer.field, initializer.field, child.name, inline.arguments
                ));
            } else {
                let expression = initializer
                    .expression
                    .as_deref()
                    .unwrap_or(&initializer.field);
                output.push_str(&format!(
                    "let __rpp_{}_value = {};\n",
                    initializer.field, expression
                ));
            }
        }
        output.push_str("let data = Self {\n");
        for initializer in &class.constructor.initializers {
            let suffix = if initializer.inline.is_some() {
                "data"
            } else {
                "value"
            };
            output.push_str(&format!(
                "{}: __rpp_{}_{suffix},\n",
                initializer.field, initializer.field
            ));
        }
        for base in &class.bases {
            output.push_str(&format!(
                "{}: {}_data,\n",
                base_data_field(base.class),
                base_data_field(base.class)
            ));
        }
        output.push_str(&format!("}};\nlet frame = {frame} {{\n"));
        for base in &class.bases {
            output.push_str(&format!(
                "{}: {}_frame,\n",
                base_frame_field(base.class),
                base_frame_field(base.class)
            ));
        }
        for initializer in &inline_initializers {
            output.push_str(&format!(
                "__rpp_{}: __rpp_{}_frame,\n",
                initializer.field, initializer.field
            ));
        }
        for param in &class.activation_params {
            output.push_str(&format!("{},\n", param.name));
        }
        output.push_str("};\n(data, frame)\n}\n");
        output.push_str(&format!(
            "#[allow(unreachable_code)]\nfn __rpp_init(&mut self, frame: {frame}) {{\n"
        ));
        if class.activation_params.is_empty() && !has_subobjects {
            output.push_str("let _ = frame;\n");
        } else {
            output.push_str(&format!("let {frame} {{ "));
            for base in &class.bases {
                let field = base_frame_field(base.class);
                output.push_str(&format!("{field}: {field}_value,"));
            }
            for initializer in &inline_initializers {
                output.push_str(&format!(
                    "__rpp_{}: __rpp_{}_frame,",
                    initializer.field, initializer.field
                ));
            }
            for param in &class.activation_params {
                output.push_str(&format!("{},", param.name));
            }
            output.push_str(" } = frame;\n");
        }
        if has_subobjects {
            output.push_str(&format!(
                "// SAFETY [SC-STAGE-VIEW]: the guard points to this uniquely borrowed final Data only for this activation call.\nlet mut guard = {activation_guard} {{ data: self as *mut _, completed: 0 }};\n"
            ));
            for base in &class.bases {
                let data_field = base_data_field(base.class);
                let frame_field = base_frame_field(base.class);
                output.push_str(&format!(
                    "self.{data_field}.__rpp_init({frame_field}_value);\nguard.completed += 1;\n"
                ));
            }
            for initializer in &inline_initializers {
                output.push_str(&format!(
                    "self.{}.__rpp_init(__rpp_{}_frame);\nguard.completed += 1;\n",
                    initializer.field, initializer.field
                ));
            }
        }
        if class.abstract_ {
            output.push_str(&class.init_body);
        } else {
            output.push_str(&format!(
                "// SAFETY [SC-STAGE-VIEW, SC-DATA-STORAGE-LAYOUT]: the helper preserves this unique Data borrow's lifetime in the transparent current-class stage view.\nlet stage = unsafe {{ __rpp_borrow_stage_{}(self) }};\nlet _ = &stage;\n",
                class.id.0
            ));
            output.push_str(&rewrite_lifecycle_body(module, class, &class.init_body));
        }
        if has_subobjects {
            output.push_str("\nguard.completed = 0;\n");
        }
        output.push_str(
            "\n}\n#[allow(unreachable_code, unused_mut, unused_variables)]\nfn __rpp_deinit(&mut self) {\n",
        );
        if has_subobjects {
            output.push_str(&format!(
                "// SAFETY [SC-STAGE-VIEW]: the guard owns all remaining deactivation obligations for this uniquely borrowed Data during unwinding.\nlet mut guard = {deactivation_guard} {{ data: self as *mut _, remaining: {} }};\n",
                class.bases.len() + inline_initializers.len()
            ));
        }
        if class.abstract_ {
            output.push_str(&class.deinit_body);
        } else {
            output.push_str(&format!(
                "// SAFETY [SC-STAGE-VIEW, SC-DATA-STORAGE-LAYOUT]: the helper preserves this unique Data borrow's lifetime in the transparent current-class stage view.\nlet stage = unsafe {{ __rpp_borrow_stage_{}(self) }};\nlet _ = &stage;\n",
                class.id.0
            ));
            output.push_str(&rewrite_lifecycle_body(module, class, &class.deinit_body));
        }
        for initializer in inline_initializers.iter().rev() {
            output.push_str(&format!(
                "\nguard.remaining -= 1;\nself.{}.__rpp_deinit();\n",
                initializer.field
            ));
        }
        for base in class.bases.iter().rev() {
            output.push_str(&format!(
                "\nguard.remaining -= 1;\nself.{}.__rpp_deinit();\n",
                base_data_field(base.class)
            ));
        }
        if has_subobjects {
            output.push_str("\nguard.remaining = 0;\n");
        }
        output.push_str("\n}\n");
        output.push_str("}\n");
        if let Some(body) = &class.drop_body {
            output.push_str(&format!("impl Drop for {data} {{ fn drop(&mut self) {{\n"));
            output.push_str(body);
            output.push_str("\n} }\n");
        }

        output.push_str(&format!(
            "#[allow(dead_code)]\n#[repr(transparent)]\nstruct {storage}({data});\n"
        ));
        let storage_deinit = if class.abstract_ {
            "__rpp_deinit"
        } else {
            "__rpp_deinit_complete"
        };
        output.push_str(&format!(
            "impl Drop for {storage} {{ fn drop(&mut self) {{ self.0.{storage_deinit}(); }} }}\n"
        ));
        if !class.abstract_ {
            let direct_guard = format!("__RppDirectGuard{}", class.id.0);
            let structural_guard = format!("__RppDirectStructuralGuard{}", class.id.0);
            output.push_str(&format!(
                "struct {structural_guard} {{ data: *mut {data} }}\n\
                 impl Drop for {structural_guard} {{ fn drop(&mut self) {{\n\
                 // SAFETY [SC-ACTIVATION-COMMIT]: the direct-place guard uniquely owns initialized Data in compiler-created MaybeUninit storage.\n\
                 unsafe {{ std::ptr::drop_in_place(self.data); }}\n\
                 }} }}\n\
                 struct {direct_guard} {{ data: *mut {data}, live: bool }}\n\
                 impl Drop for {direct_guard} {{ fn drop(&mut self) {{\n\
                 let structural = {structural_guard} {{ data: self.data }};\n\
                 if self.live {{\n\
                 // SAFETY [SC-STAGE-VIEW]: a live direct-place guard uniquely owns the complete object and consumes its deactivation obligation once.\n\
                 unsafe {{ (*self.data).__rpp_deinit_complete(); }}\n\
                 }}\n\
                 drop(structural);\n\
                 }} }}\n"
            ));
        }
        output.push_str(&format!("mod {seal_module} {{ pub trait Sealed {{}} }}\n"));
        let public_bases: Vec<_> = class
            .bases
            .iter()
            .filter(|base| base.visibility == crate::hir::BaseVisibility::Public)
            .map(|base| class_by_id(module, base.class))
            .collect();
        let has_private_interface = class.methods.iter().any(|method| {
            !method.public
                && (matches!(method.kind, crate::hir::MethodKind::NonVirtual)
                    || method.slot == Some(method.id))
        });
        if has_private_interface {
            output.push_str("#[allow(private_bounds)]\n");
        }
        output.push_str(&format!("pub trait {view}: RustppObject"));
        for base in &public_bases {
            output.push_str(&format!(" + {}View", base.name));
        }
        if has_private_interface {
            output.push_str(&format!(" + __{}Internal", class.name));
        }
        output.push_str(&format!(" + {seal_module}::Sealed {{\n"));
        for method in class.methods.iter().filter(|method| {
            method.public
                && (matches!(method.kind, crate::hir::MethodKind::NonVirtual)
                    || method.slot == Some(method.id))
        }) {
            output.push_str(&backend_trait_method_signature(module, &method.signature));
            output.push_str(";\n");
        }
        output.push_str("}\n");
        let internal_trait = format!("__{}Internal", class.name);
        let private_methods: Vec<_> = class
            .methods
            .iter()
            .filter(|method| {
                !method.public
                    && (matches!(method.kind, crate::hir::MethodKind::NonVirtual)
                        || method.slot == Some(method.id))
            })
            .collect();
        if !private_methods.is_empty() {
            output.push_str(&format!("trait {internal_trait} {{\n"));
            for method in &private_methods {
                output.push_str(&backend_trait_method_signature(module, &method.signature));
                output.push_str(";\n");
            }
            output.push_str("}\n");
        }
        if !class.abstract_ {
            emit_type_descriptor(&mut output, abi_identity, module, class, &storage);
            let stage = stage_name(class.id);
            for target in class_view_closure(module, class.id) {
                emit_shared_view_method_macro(&mut output, module, class.id, target);
                emit_shared_internal_method_macro(&mut output, module, class.id, target);
            }
            output.push_str(&format!(
                "#[allow(dead_code)] #[repr(transparent)] struct {stage}({data});\n\
                 unsafe fn __rpp_borrow_stage_{}(data: &mut {data}) -> &mut {stage} {{\n\
                 // SAFETY [SC-STAGE-VIEW, SC-DATA-STORAGE-LAYOUT]: transparent stage layout matches Data and the output lifetime is tied to the input borrow.\n\
                 unsafe {{ &mut *(data as *mut {data}).cast::<{stage}>() }}\n\
                 }}\n\
                 impl __rpp_runtime_object_sealed::Sealed for {stage} {{}}\n\
                 impl RustppObject for {stage} {{\n\
                 fn __rpp_complete_address(&self) -> usize {{ self as *const Self as usize }}\n\
                 fn __rpp_type_desc(&self) -> &'static __RppTypeDesc {{ &{} }}\n\
                 }}\n",
                class.id.0,
                type_descriptor_name(class.id)
            ));
            for target in class_view_closure(module, class.id) {
                let target_seal = format!("__rpp_{}_sealed", target.name.to_lowercase());
                output.push_str(&format!(
                    "impl {target_seal}::Sealed for {stage} {{}}\nimpl {}View for {stage} {{\n",
                    target.name
                ));
                output.push_str(&format!(
                    "{}!();\n",
                    shared_view_method_macro_name(class.id, target.id)
                ));
                output.push_str("}\n");
                emit_shared_internal_method_impl(&mut output, class.id, target, &stage);
            }
            output.push_str(&format!(
                "impl __rpp_runtime_object_sealed::Sealed for {storage} {{}}\nimpl RustppObject for {storage} {{ fn __rpp_complete_address(&self) -> usize {{ self as *const Self as usize }} fn __rpp_type_desc(&self) -> &'static __RppTypeDesc {{ &{} }} }}\n",
                type_descriptor_name(class.id)
            ));
            for target in class_view_closure(module, class.id) {
                let target_seal = format!("__rpp_{}_sealed", target.name.to_lowercase());
                output.push_str(&format!(
                    "impl {target_seal}::Sealed for {storage} {{}}\nimpl {}View for {storage} {{\n",
                    target.name
                ));
                output.push_str(&format!(
                    "{}!();\n",
                    shared_view_method_macro_name(class.id, target.id)
                ));
                output.push_str("}\n");
                emit_shared_internal_method_impl(&mut output, class.id, target, &storage);
            }
            emit_rooted_ancestor_stages(&mut output, abi_identity, module, class);
            emit_complete_lifecycle(&mut output, module, class);
        }
        output.push_str(&format!("pub type {box_owner} = Box<dyn {view}>;\n"));
        output.push_str(&format!(
            "pub type {rc_owner} = std::rc::Rc<dyn {view}>;\npub type {arc_owner} = std::sync::Arc<dyn {view}>;\n"
        ));
        output.push_str(&format!("pub struct {};\n", class.name));
        if class.abstract_ {
            continue;
        }
        output.push_str(&format!("impl {} {{\n", class.name));
        output.push_str("pub fn construct_box(");
        emit_params(&mut output, module, &class.constructor);
        output.push_str(&format!(
            ") -> {box_owner} {{\nlet (raw_data, frame) = {data}::__rpp_new("
        ));
        emit_arguments(&mut output, &class.constructor);
        output.push_str(");\n");
        output.push_str("let mut data = Box::new(raw_data);\ndata.__rpp_init_complete(frame);\n");
        output.push_str(&format!(
            "// SAFETY [SC-ACTIVATION-COMMIT, SC-DATA-STORAGE-LAYOUT]: `data` is uniquely owned, fully initialized, activated at its final allocation address, and the transparent Storage wrapper has identical layout.\nlet live: Box<{storage}> = unsafe {{ Box::from_raw(Box::into_raw(data).cast::<{storage}>()) }};\nlive\n"
        ));
        output.push_str("}\n");

        output.push_str("pub fn construct_rc(");
        emit_params(&mut output, module, &class.constructor);
        output.push_str(&format!(
            ") -> {rc_owner} {{\nlet (raw_data, frame) = {data}::__rpp_new("
        ));
        emit_arguments(&mut output, &class.constructor);
        output.push_str(");\n");
        output.push_str("let mut data = std::rc::Rc::new(raw_data);\nstd::rc::Rc::get_mut(&mut data).expect(\"construction owner must be unique\").__rpp_init_complete(frame);\n");
        output.push_str(&format!(
            "// SAFETY [SC-ACTIVATION-COMMIT, SC-DATA-STORAGE-LAYOUT]: construction retains the only Rc owner until activation succeeds; the allocation is unchanged and the transparent Storage wrapper has identical layout.\nlet live: std::rc::Rc<{storage}> = unsafe {{ std::rc::Rc::from_raw(std::rc::Rc::into_raw(data).cast::<{storage}>()) }};\nlive\n"
        ));
        output.push_str("}\n");

        output.push_str("pub fn construct_arc(");
        emit_params(&mut output, module, &class.constructor);
        output.push_str(&format!(
            ") -> {arc_owner} {{\nlet (raw_data, frame) = {data}::__rpp_new("
        ));
        emit_arguments(&mut output, &class.constructor);
        output.push_str(");\n");
        output.push_str("let mut data = std::sync::Arc::new(raw_data);\nstd::sync::Arc::get_mut(&mut data).expect(\"construction owner must be unique\").__rpp_init_complete(frame);\n");
        output.push_str(&format!(
            "// SAFETY [SC-ACTIVATION-COMMIT, SC-DATA-STORAGE-LAYOUT]: construction retains the only Arc owner and publishes no Weak reference until activation succeeds; the allocation is unchanged and the transparent Storage wrapper has identical layout.\nlet live: std::sync::Arc<{storage}> = unsafe {{ std::sync::Arc::from_raw(std::sync::Arc::into_raw(data).cast::<{storage}>()) }};\nlive\n"
        ));
        output.push_str("}\n}\n");
    }

    emit_cast_helpers(&mut output, abi_identity, module);

    for item in &module.rust_items {
        output.push_str(&item.source);
        output.push('\n');
    }

    syn::parse_file(&output).map_err(|error| {
        vec![Diagnostic::internal(format!(
            "internal error: generated invalid Rust: {error}"
        ))]
    })?;
    Ok(output)
}

fn validate_backend_plans(module: &Module) -> Result<(), Vec<Diagnostic>> {
    for class in &module.value_classes {
        if class.fields.iter().any(|field| field.id.owner != class.id) {
            return Err(vec![Diagnostic::internal(
                "internal error: value-class field belongs to the wrong semantic owner",
            )]);
        }
    }
    for class in &module.classes {
        if class.fields.iter().any(|field| field.id.owner != class.id) {
            return Err(vec![Diagnostic::internal(
                "internal error: ordinary-class field belongs to the wrong semantic owner",
            )]);
        }
        let activation_ids: Vec<_> = class
            .lifecycle
            .activation
            .iter()
            .map(|step| match step {
                LifecycleStep::ActivateClass(id) => *id,
                LifecycleStep::DeactivateClass(_) => unreachable!(),
            })
            .collect();
        let deactivation_ids: Vec<_> = class
            .lifecycle
            .deactivation
            .iter()
            .map(|step| match step {
                LifecycleStep::DeactivateClass(id) => *id,
                LifecycleStep::ActivateClass(_) => unreachable!(),
            })
            .collect();
        let mut expected_deactivation = activation_ids.clone();
        expected_deactivation.reverse();
        let visibility_is_valid = class.bases.iter().all(|base| {
            matches!(
                base.visibility,
                crate::hir::BaseVisibility::Public
                    | crate::hir::BaseVisibility::Protected
                    | crate::hir::BaseVisibility::Private
            )
        });
        if activation_ids.last() != Some(&class.id)
            || deactivation_ids != expected_deactivation
            || !visibility_is_valid
        {
            return Err(vec![Diagnostic::internal(
                "internal error: unsupported or inconsistent lifecycle plan",
            )]);
        }
    }
    Ok(())
}

fn emit_params(output: &mut String, module: &Module, constructor: &Constructor) {
    for (index, param) in constructor.params.iter().enumerate() {
        if index > 0 {
            output.push_str(", ");
        }
        output.push_str(&format!(
            "{}: {}",
            param.name,
            backend_type(module, &param.ty)
        ));
    }
}

fn backend_type(module: &Module, ty: &TypeRef) -> String {
    let class_name = |id| {
        module
            .classes
            .iter()
            .find(|class| class.id == id)
            .map(|class| class.name.as_str())
            .expect("resolved class ID must exist")
    };
    match ty.kind {
        TypeKind::Value => backend_value_type(module, &ty.source),
        TypeKind::InvalidClassValue(_) => ty.source.clone(),
        TypeKind::ExactClass(id) => format!("__{}Data", class_name(id)),
        TypeKind::ClassOwner { owner, class } => {
            let suffix = match owner {
                OwnerKind::Box => "Box",
                OwnerKind::Rc => "Rc",
                OwnerKind::Arc => "Arc",
            };
            format!("{}{suffix}", class_name(class))
        }
        TypeKind::ClassBorrow { mutable, class } => {
            let mutability = if mutable { "mut " } else { "" };
            format!("&{mutability}dyn {}View", class_name(class))
        }
    }
}

struct BackendTypeLowerer<'a> {
    module: &'a Module,
}

impl BackendTypeLowerer<'_> {
    fn class_name(&self, ty: &syn::Type) -> Option<&str> {
        let syn::Type::Path(path) = ty else {
            return None;
        };
        if path.qself.is_some() || path.path.segments.len() != 1 {
            return None;
        }
        let segment = path.path.segments.first().unwrap();
        if !matches!(segment.arguments, syn::PathArguments::None) {
            return None;
        }
        self.module
            .classes
            .iter()
            .find(|class| segment.ident == class.name.as_str())
            .map(|class| class.name.as_str())
    }
}

impl syn::fold::Fold for BackendTypeLowerer<'_> {
    fn fold_type_reference(&mut self, mut reference: syn::TypeReference) -> syn::TypeReference {
        if let Some(class) = self.class_name(&reference.elem) {
            reference.elem = Box::new(
                syn::parse_str::<syn::Type>(&format!("dyn {class}View"))
                    .expect("generated class-view reference type must parse"),
            );
            reference
        } else {
            syn::fold::fold_type_reference(self, reference)
        }
    }

    fn fold_type_path(&mut self, path: syn::TypePath) -> syn::TypePath {
        if path.qself.is_none()
            && path.path.segments.len() == 1
            && let Some(segment) = path.path.segments.first()
            && matches!(segment.ident.to_string().as_str(), "Box" | "Rc" | "Arc")
            && let syn::PathArguments::AngleBracketed(arguments) = &segment.arguments
            && arguments.args.len() == 1
            && let Some(syn::GenericArgument::Type(inner)) = arguments.args.first()
            && let Some(class) = self.class_name(inner)
        {
            return syn::parse_str::<syn::TypePath>(&format!("{class}{}", segment.ident))
                .expect("generated class owner alias must parse");
        }
        syn::fold::fold_type_path(self, path)
    }
}

fn backend_value_type(module: &Module, source: &str) -> String {
    use quote::ToTokens;
    use syn::fold::Fold;
    let Ok(ty) = syn::parse_str::<syn::Type>(source) else {
        return source.to_owned();
    };
    BackendTypeLowerer { module }
        .fold_type(ty)
        .to_token_stream()
        .to_string()
}

fn backend_method_signature(module: &Module, source: &str) -> String {
    use quote::ToTokens;
    use syn::fold::Fold;

    let signature = syn::parse_str::<syn::Signature>(source)
        .expect("method signatures were validated during HIR lowering");
    BackendTypeLowerer { module }
        .fold_signature(signature)
        .to_token_stream()
        .to_string()
}

fn backend_trait_method_signature(module: &Module, source: &str) -> String {
    use quote::ToTokens;
    use syn::fold::Fold;

    let signature = syn::parse_str::<syn::Signature>(source)
        .expect("method signatures were validated during HIR lowering");
    let mut signature = BackendTypeLowerer { module }.fold_signature(signature);
    for input in &mut signature.inputs {
        if let syn::FnArg::Typed(input) = input
            && let syn::Pat::Ident(pattern) = input.pat.as_mut()
        {
            pattern.by_ref = None;
            pattern.mutability = None;
            pattern.subpat = None;
        }
    }
    signature.to_token_stream().to_string()
}

fn emit_arguments(output: &mut String, constructor: &Constructor) {
    for (index, param) in constructor.params.iter().enumerate() {
        if index > 0 {
            output.push_str(", ");
        }
        output.push_str(&param.name);
    }
}

fn class_by_id(module: &Module, id: crate::hir::ClassId) -> &crate::hir::Class {
    module
        .classes
        .iter()
        .find(|class| class.id == id)
        .expect("resolved class ID must exist")
}

fn base_data_field(id: crate::hir::ClassId) -> String {
    format!("__rpp_base_{}", id.0)
}

fn base_frame_field(id: crate::hir::ClassId) -> String {
    format!("__rpp_base_{}_frame", id.0)
}

fn class_view_closure(module: &Module, root: crate::hir::ClassId) -> Vec<&crate::hir::Class> {
    fn visit<'a>(
        module: &'a Module,
        id: crate::hir::ClassId,
        seen: &mut std::collections::HashSet<crate::hir::ClassId>,
        output: &mut Vec<&'a crate::hir::Class>,
    ) {
        if !seen.insert(id) {
            return;
        }
        let class = class_by_id(module, id);
        for base in &class.bases {
            visit(module, base.class, seen, output);
        }
        output.push(class);
    }

    let mut seen = std::collections::HashSet::new();
    let mut output = Vec::new();
    visit(module, root, &mut seen, &mut output);
    output
}

fn resolve_slot_implementation(
    module: &Module,
    complete: crate::hir::ClassId,
    slot: crate::hir::MethodId,
) -> &crate::hir::Method {
    try_resolve_slot_implementation(module, complete, slot)
        .expect("concrete class must implement every inherited virtual slot")
}

fn try_resolve_slot_implementation(
    module: &Module,
    complete: crate::hir::ClassId,
    slot: crate::hir::MethodId,
) -> Option<&crate::hir::Method> {
    class_view_closure(module, complete)
        .into_iter()
        .rev()
        .flat_map(|class| class.methods.iter())
        .find(|method| method.slot == Some(slot) && method.body.is_some())
}

fn rewrite_method_body(
    module: &Module,
    complete: crate::hir::ClassId,
    method: &crate::hir::Method,
) -> String {
    use quote::ToTokens;
    use syn::fold::Fold;

    struct FieldRewriter {
        projections: std::collections::HashMap<String, String>,
    }

    impl Fold for FieldRewriter {
        fn fold_expr_field(&mut self, field: syn::ExprField) -> syn::ExprField {
            let field = syn::fold::fold_expr_field(self, field);
            let syn::Member::Named(member) = &field.member else {
                return field;
            };
            let syn::Expr::Path(base) = field.base.as_ref() else {
                return field;
            };
            if !base.path.is_ident("self") {
                return field;
            }
            let Some(projection) = self.projections.get(&member.to_string()) else {
                return field;
            };
            syn::parse_str::<syn::ExprField>(&format!("{projection}.{member}"))
                .expect("generated field projection must parse")
        }
    }

    let mut projections = std::collections::HashMap::new();
    let defining = class_by_id(module, method.id.owner);
    for visible in class_view_closure(module, defining.id) {
        let mut base = String::from("self.0");
        for step in projection_path(module, complete, visible.id)
            .expect("unique concrete field projection must exist")
        {
            base.push('.');
            base.push_str(&base_data_field(step));
        }
        for field in visible
            .fields
            .iter()
            .filter(|field| visible.id == defining.id || field.public)
        {
            projections
                .entry(field.name.clone())
                .or_insert(base.clone());
        }
    }
    let body = method
        .body
        .as_deref()
        .expect("concrete method implementation must have a body");
    let block = syn::parse_str::<syn::Block>(&format!("{{{body}}}")).unwrap_or_else(|error| {
        panic!(
            "method `{}` body must be valid Rust-compatible syntax after lowering: {error}; body: {body}",
            method.name
        )
    });
    let rewritten = FieldRewriter { projections }.fold_block(block);
    rewritten
        .stmts
        .iter()
        .map(ToTokens::to_token_stream)
        .map(|tokens| tokens.to_string())
        .collect::<Vec<_>>()
        .join(" ")
}

fn projection_path(
    module: &Module,
    current: crate::hir::ClassId,
    target: crate::hir::ClassId,
) -> Option<Vec<crate::hir::ClassId>> {
    if current == target {
        return Some(Vec::new());
    }
    for base in &class_by_id(module, current).bases {
        if let Some(mut tail) = projection_path(module, base.class, target) {
            let mut path = vec![base.class];
            path.append(&mut tail);
            return Some(path);
        }
    }
    None
}

fn stage_name(id: crate::hir::ClassId) -> String {
    format!("__RppStage{}", id.0)
}

fn rooted_stage_name(complete: crate::hir::ClassId, active: crate::hir::ClassId) -> String {
    if complete == active {
        stage_name(complete)
    } else {
        format!("__RppStage{}As{}", complete.0, active.0)
    }
}

fn rooted_stage_descriptor_name(
    complete: crate::hir::ClassId,
    active: crate::hir::ClassId,
) -> String {
    if complete == active {
        type_descriptor_name(complete)
    } else {
        format!("__RPP_DESC_{}_AS_{}", complete.0, active.0)
    }
}

fn rewrite_lifecycle_body(module: &Module, class: &crate::hir::Class, body: &str) -> String {
    rewrite_rooted_lifecycle_body(module, class.id, class, body)
}

fn rewrite_rooted_lifecycle_body(
    module: &Module,
    complete: crate::hir::ClassId,
    class: &crate::hir::Class,
    body: &str,
) -> String {
    use quote::ToTokens;
    use syn::fold::Fold;

    struct LifecycleRewriter {
        projections: std::collections::HashMap<String, String>,
    }

    impl Fold for LifecycleRewriter {
        fn fold_macro(&mut self, mut item: syn::Macro) -> syn::Macro {
            item.tokens = rewrite_lifecycle_macro_tokens(item.tokens, &self.projections);
            item
        }

        fn fold_expr_path(&mut self, path: syn::ExprPath) -> syn::ExprPath {
            if path.path.to_token_stream().to_string() == "self" {
                syn::parse_quote!(stage)
            } else {
                path
            }
        }

        fn fold_expr(&mut self, expression: syn::Expr) -> syn::Expr {
            if let syn::Expr::Field(field) = &expression
                && let syn::Member::Named(member) = &field.member
                && let syn::Expr::Path(base) = field.base.as_ref()
                && base.path.to_token_stream().to_string() == "self"
                && let Some(projection) = self.projections.get(&member.to_string())
            {
                return syn::parse_str::<syn::Expr>(&format!("{projection}.{member}"))
                    .expect("generated lifecycle field projection must parse");
            }
            if let syn::Expr::Path(path) = &expression
                && path.path.to_token_stream().to_string() == "self"
            {
                return syn::parse_quote!(stage);
            }
            syn::fold::fold_expr(self, expression)
        }
    }

    let mut projections = std::collections::HashMap::new();
    for visible in class_view_closure(module, class.id) {
        let mut base = String::from("stage.0");
        for step in projection_path(module, complete, visible.id)
            .expect("unique lifecycle field projection must exist")
        {
            base.push('.');
            base.push_str(&base_data_field(step));
        }
        for field in visible
            .fields
            .iter()
            .filter(|field| visible.id == class.id || field.public)
        {
            projections
                .entry(field.name.clone())
                .or_insert(base.clone());
        }
    }
    let block = syn::parse_str::<syn::Block>(&format!("{{{body}}}"))
        .expect("lifecycle bodies must be valid Rust-compatible blocks");
    let rewritten = LifecycleRewriter { projections }.fold_block(block);
    rewritten
        .stmts
        .iter()
        .map(ToTokens::to_token_stream)
        .map(|tokens| tokens.to_string())
        .collect::<Vec<_>>()
        .join(" ")
}

fn rewrite_lifecycle_macro_tokens(
    tokens: proc_macro2::TokenStream,
    projections: &std::collections::HashMap<String, String>,
) -> proc_macro2::TokenStream {
    use proc_macro2::{Group, Ident, TokenStream, TokenTree};
    let input: Vec<_> = tokens.into_iter().collect();
    let mut output = TokenStream::new();
    let mut index = 0usize;
    while index < input.len() {
        match &input[index] {
            TokenTree::Group(group) => {
                let mut rewritten = Group::new(
                    group.delimiter(),
                    rewrite_lifecycle_macro_tokens(group.stream(), projections),
                );
                rewritten.set_span(group.span());
                output.extend([TokenTree::Group(rewritten)]);
                index += 1;
            }
            TokenTree::Ident(ident) if ident == "self" => {
                let field_name = match (input.get(index + 1), input.get(index + 2)) {
                    (Some(TokenTree::Punct(dot)), Some(TokenTree::Ident(field)))
                        if dot.as_char() == '.' =>
                    {
                        Some(field.to_string())
                    }
                    _ => None,
                };
                if let Some(projection) =
                    field_name.as_ref().and_then(|field| projections.get(field))
                {
                    let replacement: TokenStream =
                        format!("{projection}.{}", field_name.as_deref().unwrap())
                            .parse()
                            .expect("generated macro field projection must tokenize");
                    output.extend(replacement);
                    index += 3;
                } else {
                    output.extend([TokenTree::Ident(Ident::new("stage", ident.span()))]);
                    index += 1;
                }
            }
            token => {
                output.extend([token.clone()]);
                index += 1;
            }
        }
    }
    output
}

fn type_descriptor_name(id: crate::hir::ClassId) -> String {
    format!("__RPP_DESC_{}", id.0)
}

fn cast_const_thunk_name(complete: crate::hir::ClassId, target: crate::hir::ClassId) -> String {
    format!("__rpp_cast_{}_{}_const", complete.0, target.0)
}

fn cast_mut_thunk_name(complete: crate::hir::ClassId, target: crate::hir::ClassId) -> String {
    format!("__rpp_cast_{}_{}_mut", complete.0, target.0)
}

fn emit_type_descriptor(
    output: &mut String,
    source_name: &str,
    module: &Module,
    class: &crate::hir::Class,
    storage: &str,
) {
    let targets = class_view_closure(module, class.id);
    for target in &targets {
        let const_thunk = cast_const_thunk_name(class.id, target.id);
        let mut_thunk = cast_mut_thunk_name(class.id, target.id);
        output.push_str(&format!(
            "unsafe fn {const_thunk}(root: *const (), out: *mut ()) {{\n\
             let storage = root.cast::<{storage}>();\n\
             let view: *const dyn {}View = storage;\n\
             // SAFETY [SC-CAST-THUNK]: `out` points to writable storage for exactly one target trait-object pointer and Rust created its metadata.\n\
             unsafe {{ out.cast::<*const dyn {}View>().write(view); }}\n\
             }}\n",
            target.name, target.name
        ));
        output.push_str(&format!(
            "unsafe fn {mut_thunk}(root: *mut (), out: *mut ()) {{\n\
             let storage = root.cast::<{storage}>();\n\
             let view: *mut dyn {}View = storage;\n\
             // SAFETY [SC-CAST-THUNK]: `out` points to writable storage for exactly one target trait-object pointer and the root is uniquely borrowed.\n\
             unsafe {{ out.cast::<*mut dyn {}View>().write(view); }}\n\
             }}\n",
            target.name, target.name
        ));
    }
    let id = stable_class_id(source_name, &class.name);
    output.push_str(&format!(
        "static {}: __RppTypeDesc = __RppTypeDesc {{ active_class: __RppClassId({id}), complete_storage_class: __RppClassId({id}), casts: &[\n",
        type_descriptor_name(class.id)
    ));
    for target in targets {
        output.push_str(&format!(
            "__RppCastEntry {{ target: __RppClassId({}), make_const: {}, make_mut: {} }},\n",
            stable_class_id(source_name, &target.name),
            cast_const_thunk_name(class.id, target.id),
            cast_mut_thunk_name(class.id, target.id)
        ));
    }
    output.push_str("] };\n");
}

fn emit_rooted_ancestor_stages(
    output: &mut String,
    source_name: &str,
    module: &Module,
    complete: &crate::hir::Class,
) {
    let complete_data = format!("__{}Data", complete.name);
    for active in class_view_closure(module, complete.id)
        .into_iter()
        .filter(|active| active.id != complete.id)
    {
        let stage = rooted_stage_name(complete.id, active.id);
        let descriptor = rooted_stage_descriptor_name(complete.id, active.id);
        output.push_str(&format!(
            "#[allow(dead_code)] #[repr(transparent)] struct {stage}({complete_data});\n\
             unsafe fn __rpp_borrow_rooted_stage_{}_{}(data: &mut {complete_data}) -> &mut {stage} {{\n\
             // SAFETY [SC-STAGE-VIEW, SC-DATA-STORAGE-LAYOUT]: transparent rooted-stage layout matches complete Data and the output lifetime is tied to the input borrow.\n\
             unsafe {{ &mut *(data as *mut {complete_data}).cast::<{stage}>() }}\n\
             }}\n\
             impl __rpp_runtime_object_sealed::Sealed for {stage} {{}}\n\
             impl RustppObject for {stage} {{\n\
             fn __rpp_complete_address(&self) -> usize {{ self as *const Self as usize }}\n\
             fn __rpp_type_desc(&self) -> &'static __RppTypeDesc {{ &{descriptor} }}\n\
             }}\n",
            complete.id.0,
            active.id.0
        ));
        let targets = class_view_closure(module, active.id);
        for target in &targets {
            let target_seal = format!("__rpp_{}_sealed", target.name.to_lowercase());
            output.push_str(&format!(
                "impl {target_seal}::Sealed for {stage} {{}}\nimpl {}View for {stage} {{\n",
                target.name
            ));
            for method in target.methods.iter().filter(|method| {
                method.public
                    && (matches!(method.kind, crate::hir::MethodKind::NonVirtual)
                        || method.slot == Some(method.id))
            }) {
                let implementation = method
                    .slot
                    .and_then(|slot| try_resolve_slot_implementation(module, active.id, slot))
                    .or_else(|| method.body.as_ref().map(|_| method));
                if let Some(implementation) = implementation {
                    output.push_str(&backend_method_signature(module, &implementation.signature));
                    output.push_str(" {\n");
                    output.push_str(&rewrite_method_body(module, complete.id, implementation));
                    output.push_str("\n}\n");
                } else {
                    output.push_str(&backend_method_signature(module, &method.signature));
                    output.push_str(
                        " { panic!(\"abstract virtual slot invoked during its lifecycle stage\") }\n",
                    );
                }
            }
            output.push_str("}\n");
            emit_internal_method_impl(output, module, complete.id, active.id, target, &stage);
        }

        for target in &targets {
            let const_thunk = format!(
                "__rpp_stage_cast_{}_{}_{}_const",
                complete.id.0, active.id.0, target.id.0
            );
            let mut_thunk = format!(
                "__rpp_stage_cast_{}_{}_{}_mut",
                complete.id.0, active.id.0, target.id.0
            );
            output.push_str(&format!(
                "unsafe fn {const_thunk}(root: *const (), out: *mut ()) {{\n\
                 let stage = root.cast::<{stage}>();\n\
                 let view: *const dyn {}View = stage;\n\
                 // SAFETY [SC-CAST-THUNK]: `out` points to writable storage for one stage-bounded target trait-object pointer.\n\
                 unsafe {{ out.cast::<*const dyn {}View>().write(view); }}\n\
                 }}\n",
                target.name, target.name
            ));
            output.push_str(&format!(
                "unsafe fn {mut_thunk}(root: *mut (), out: *mut ()) {{\n\
                 let stage = root.cast::<{stage}>();\n\
                 let view: *mut dyn {}View = stage;\n\
                 // SAFETY [SC-CAST-THUNK]: `out` points to writable storage for one uniquely borrowed stage-bounded target pointer.\n\
                 unsafe {{ out.cast::<*mut dyn {}View>().write(view); }}\n\
                 }}\n",
                target.name, target.name
            ));
        }
        output.push_str(&format!(
            "static {descriptor}: __RppTypeDesc = __RppTypeDesc {{ active_class: __RppClassId({}), complete_storage_class: __RppClassId({}), casts: &[\n",
            stable_class_id(source_name, &active.name),
            stable_class_id(source_name, &complete.name)
        ));
        for target in targets {
            output.push_str(&format!(
                "__RppCastEntry {{ target: __RppClassId({}), make_const: __rpp_stage_cast_{}_{}_{}_const, make_mut: __rpp_stage_cast_{}_{}_{}_mut }},\n",
                stable_class_id(source_name, &target.name),
                complete.id.0,
                active.id.0,
                target.id.0,
                complete.id.0,
                active.id.0,
                target.id.0
            ));
        }
        output.push_str("] };\n");
    }
}

fn rooted_init_name(active: crate::hir::ClassId) -> String {
    format!("__rpp_init_stage_{}", active.0)
}

fn rooted_deinit_name(active: crate::hir::ClassId) -> String {
    format!("__rpp_deinit_stage_{}", active.0)
}

fn rooted_data_path(
    module: &Module,
    complete: crate::hir::ClassId,
    active: crate::hir::ClassId,
    root: &str,
) -> String {
    let mut path = root.to_owned();
    for step in projection_path(module, complete, active)
        .expect("lifecycle stage must be a unique concrete base of the complete class")
    {
        path.push('.');
        path.push_str(&base_data_field(step));
    }
    path
}

fn rooted_activation_guard_name(
    complete: crate::hir::ClassId,
    active: crate::hir::ClassId,
) -> String {
    format!("__RppRootActivationGuard{}At{}", complete.0, active.0)
}

fn rooted_deactivation_guard_name(
    complete: crate::hir::ClassId,
    active: crate::hir::ClassId,
) -> String {
    format!("__RppRootDeactivationGuard{}At{}", complete.0, active.0)
}

fn emit_complete_lifecycle(output: &mut String, module: &Module, complete: &crate::hir::Class) {
    let data = format!("__{}Data", complete.name);
    let stages = class_view_closure(module, complete.id);

    for active in &stages {
        let inline: Vec<_> = active
            .constructor
            .initializers
            .iter()
            .filter(|initializer| initializer.inline.is_some())
            .collect();
        if active.bases.is_empty() && inline.is_empty() {
            continue;
        }
        let activation_guard = rooted_activation_guard_name(complete.id, active.id);
        let deactivation_guard = rooted_deactivation_guard_name(complete.id, active.id);
        output.push_str(&format!(
            "struct {activation_guard} {{ data: *mut {data}, completed: usize }}\nimpl Drop for {activation_guard} {{ fn drop(&mut self) {{\n// SAFETY [SC-STAGE-VIEW]: rooted rollback uniquely owns complete Data and deactivates only completed substages.\nunsafe {{\n"
        ));
        let mut index = active.bases.len() + inline.len();
        for initializer in inline.iter().rev() {
            index -= 1;
            let path = rooted_data_path(module, complete.id, active.id, "(*self.data)");
            output.push_str(&format!(
                "if self.completed > {index} {{ {path}.{}.__rpp_deinit_complete(); }}\n",
                initializer.field
            ));
        }
        for base in active.bases.iter().rev() {
            index -= 1;
            output.push_str(&format!(
                "if self.completed > {index} {{ (*self.data).{}(); }}\n",
                rooted_deinit_name(base.class)
            ));
        }
        output.push_str("} } }\n");

        output.push_str(&format!(
            "struct {deactivation_guard} {{ data: *mut {data}, remaining: usize }}\nimpl Drop for {deactivation_guard} {{ fn drop(&mut self) {{\n// SAFETY [SC-STAGE-VIEW]: rooted unwind cleanup uniquely owns complete Data and consumes remaining stages once.\nunsafe {{\n"
        ));
        let mut index = active.bases.len() + inline.len();
        for initializer in inline.iter().rev() {
            index -= 1;
            let path = rooted_data_path(module, complete.id, active.id, "(*self.data)");
            output.push_str(&format!(
                "if self.remaining > {index} {{ self.remaining = {index}; {path}.{}.__rpp_deinit_complete(); }}\n",
                initializer.field
            ));
        }
        for base in active.bases.iter().rev() {
            index -= 1;
            output.push_str(&format!(
                "if self.remaining > {index} {{ self.remaining = {index}; (*self.data).{}(); }}\n",
                rooted_deinit_name(base.class)
            ));
        }
        output.push_str("} } }\n");
    }

    output.push_str(&format!("impl {data} {{\n"));
    output.push_str(&format!(
        "fn __rpp_init_complete(&mut self, frame: __{}ActivationFrame) {{ self.{}(frame); }}\nfn __rpp_deinit_complete(&mut self) {{ self.{}(); }}\n",
        complete.name,
        rooted_init_name(complete.id),
        rooted_deinit_name(complete.id)
    ));
    for active in stages {
        emit_rooted_stage_lifecycle_methods(output, module, complete, active);
    }
    output.push_str("}\n");
}

fn emit_rooted_stage_lifecycle_methods(
    output: &mut String,
    module: &Module,
    complete: &crate::hir::Class,
    active: &crate::hir::Class,
) {
    let frame = format!("__{}ActivationFrame", active.name);
    let inline: Vec<_> = active
        .constructor
        .initializers
        .iter()
        .filter(|initializer| initializer.inline.is_some())
        .collect();
    let has_subobjects = !active.bases.is_empty() || !inline.is_empty();
    output.push_str(&format!(
        "#[allow(unreachable_code)] fn {}(&mut self, frame: {frame}) {{\n",
        rooted_init_name(active.id)
    ));
    if active.activation_params.is_empty() && !has_subobjects {
        output.push_str("let _ = frame;\n");
    } else {
        output.push_str(&format!("let {frame} {{ "));
        for base in &active.bases {
            let field = base_frame_field(base.class);
            output.push_str(&format!("{field}: {field}_value,"));
        }
        for initializer in &inline {
            output.push_str(&format!(
                "__rpp_{}: __rpp_{}_frame,",
                initializer.field, initializer.field
            ));
        }
        for param in &active.activation_params {
            output.push_str(&format!("{},", param.name));
        }
        output.push_str(" } = frame;\n");
    }
    if has_subobjects {
        output.push_str(&format!(
            "// SAFETY [SC-STAGE-VIEW]: this guard owns the completed rooted substage obligations during activation.\nlet mut guard = {} {{ data: self as *mut _, completed: 0 }};\n",
            rooted_activation_guard_name(complete.id, active.id)
        ));
        for base in &active.bases {
            output.push_str(&format!(
                "self.{}({}_value); guard.completed += 1;\n",
                rooted_init_name(base.class),
                base_frame_field(base.class)
            ));
        }
        let active_path = rooted_data_path(module, complete.id, active.id, "self");
        for initializer in &inline {
            output.push_str(&format!(
                "{active_path}.{}.__rpp_init_complete(__rpp_{}_frame); guard.completed += 1;\n",
                initializer.field, initializer.field
            ));
        }
    }
    let borrow_stage = if complete.id == active.id {
        format!("__rpp_borrow_stage_{}", active.id.0)
    } else {
        format!(
            "__rpp_borrow_rooted_stage_{}_{}",
            complete.id.0, active.id.0
        )
    };
    output.push_str(&format!(
        "// SAFETY [SC-STAGE-VIEW, SC-DATA-STORAGE-LAYOUT]: the helper preserves the complete Data borrow's lifetime in precisely the active rooted stage.\nlet stage = unsafe {{ {borrow_stage}(self) }}; let _ = &stage;\n"
    ));
    output.push_str(&rewrite_rooted_lifecycle_body(
        module,
        complete.id,
        active,
        &active.init_body,
    ));
    if has_subobjects {
        output.push_str("\nguard.completed = 0;\n");
    }
    output.push_str("}\n");

    output.push_str(&format!(
        "#[allow(unreachable_code, unused_mut, unused_variables)] fn {}(&mut self) {{\n",
        rooted_deinit_name(active.id)
    ));
    if has_subobjects {
        output.push_str(&format!(
            "// SAFETY [SC-STAGE-VIEW]: this guard owns all remaining rooted deactivation obligations during unwinding.\nlet mut guard = {} {{ data: self as *mut _, remaining: {} }};\n",
            rooted_deactivation_guard_name(complete.id, active.id),
            active.bases.len() + inline.len()
        ));
    }
    output.push_str(&format!(
        "// SAFETY [SC-STAGE-VIEW, SC-DATA-STORAGE-LAYOUT]: the helper preserves the complete Data borrow's lifetime in precisely the active rooted stage.\nlet stage = unsafe {{ {borrow_stage}(self) }}; let _ = &stage;\n"
    ));
    output.push_str(&rewrite_rooted_lifecycle_body(
        module,
        complete.id,
        active,
        &active.deinit_body,
    ));
    let active_path = rooted_data_path(module, complete.id, active.id, "self");
    for initializer in inline.iter().rev() {
        output.push_str(&format!(
            "\nguard.remaining -= 1; {active_path}.{}.__rpp_deinit_complete();\n",
            initializer.field
        ));
    }
    for base in active.bases.iter().rev() {
        output.push_str(&format!(
            "\nguard.remaining -= 1; self.{}();\n",
            rooted_deinit_name(base.class)
        ));
    }
    if has_subobjects {
        output.push_str("guard.remaining = 0;\n");
    }
    output.push_str("}\n");
}

fn emit_internal_method_impl(
    output: &mut String,
    module: &Module,
    complete: crate::hir::ClassId,
    effective: crate::hir::ClassId,
    target: &crate::hir::Class,
    backing: &str,
) {
    let methods: Vec<_> = target
        .methods
        .iter()
        .filter(|method| {
            !method.public
                && (matches!(method.kind, crate::hir::MethodKind::NonVirtual)
                    || method.slot == Some(method.id))
        })
        .collect();
    if methods.is_empty() {
        return;
    }
    output.push_str(&format!(
        "impl __{}Internal for {backing} {{\n",
        target.name
    ));
    for method in methods {
        let implementation = method
            .slot
            .and_then(|slot| try_resolve_slot_implementation(module, effective, slot))
            .or_else(|| method.body.as_ref().map(|_| method));
        if let Some(implementation) = implementation {
            output.push_str(&backend_method_signature(module, &implementation.signature));
            output.push_str(" {\n");
            output.push_str(&rewrite_method_body(module, complete, implementation));
            output.push_str("\n}\n");
        } else {
            output.push_str(&backend_method_signature(module, &method.signature));
            output.push_str(
                " { panic!(\"abstract private virtual slot invoked during its lifecycle stage\") }\n",
            );
        }
    }
    output.push_str("}\n");
}

fn shared_view_method_macro_name(
    complete: crate::hir::ClassId,
    target: crate::hir::ClassId,
) -> String {
    format!("__rpp_view_methods_{}_{}", complete.0, target.0)
}

fn shared_internal_method_macro_name(
    complete: crate::hir::ClassId,
    target: crate::hir::ClassId,
) -> String {
    format!("__rpp_internal_methods_{}_{}", complete.0, target.0)
}

/// Emits the method items shared by a complete class's fully-active lifecycle
/// stage and live Storage. The backing types must remain distinct for epoch,
/// RTTI, and Drop semantics, but their effective dynamic class is identical.
fn emit_shared_view_method_macro(
    output: &mut String,
    module: &Module,
    complete: crate::hir::ClassId,
    target: &crate::hir::Class,
) {
    let name = shared_view_method_macro_name(complete, target.id);
    output.push_str(&format!("macro_rules! {name} {{ () => {{\n"));
    for method in target.methods.iter().filter(|method| {
        method.public
            && (matches!(method.kind, crate::hir::MethodKind::NonVirtual)
                || method.slot == Some(method.id))
    }) {
        let implementation = if let Some(slot) = method.slot {
            resolve_slot_implementation(module, complete, slot)
        } else {
            method
        };
        output.push_str(&backend_method_signature(module, &implementation.signature));
        output.push_str(" {\n");
        output.push_str(&rewrite_method_body(module, complete, implementation));
        output.push_str("\n}\n");
    }
    output.push_str("} }\n");
}

fn emit_shared_internal_method_macro(
    output: &mut String,
    module: &Module,
    complete: crate::hir::ClassId,
    target: &crate::hir::Class,
) {
    let methods: Vec<_> = target
        .methods
        .iter()
        .filter(|method| {
            !method.public
                && (matches!(method.kind, crate::hir::MethodKind::NonVirtual)
                    || method.slot == Some(method.id))
        })
        .collect();
    if methods.is_empty() {
        return;
    }
    let name = shared_internal_method_macro_name(complete, target.id);
    output.push_str(&format!("macro_rules! {name} {{ () => {{\n"));
    for method in methods {
        let implementation = method
            .slot
            .and_then(|slot| try_resolve_slot_implementation(module, complete, slot))
            .or_else(|| method.body.as_ref().map(|_| method));
        if let Some(implementation) = implementation {
            output.push_str(&backend_method_signature(module, &implementation.signature));
            output.push_str(" {\n");
            output.push_str(&rewrite_method_body(module, complete, implementation));
            output.push_str("\n}\n");
        } else {
            output.push_str(&backend_method_signature(module, &method.signature));
            output.push_str(
                " { panic!(\"abstract private virtual slot invoked during its lifecycle stage\") }\n",
            );
        }
    }
    output.push_str("} }\n");
}

fn emit_shared_internal_method_impl(
    output: &mut String,
    complete: crate::hir::ClassId,
    target: &crate::hir::Class,
    backing: &str,
) {
    let has_methods = target.methods.iter().any(|method| {
        !method.public
            && (matches!(method.kind, crate::hir::MethodKind::NonVirtual)
                || method.slot == Some(method.id))
    });
    if !has_methods {
        return;
    }
    output.push_str(&format!(
        "impl __{}Internal for {backing} {{ {}!(); }}\n",
        target.name,
        shared_internal_method_macro_name(complete, target.id)
    ));
}

fn emit_cast_helpers(output: &mut String, source_name: &str, module: &Module) {
    for target in &module.classes {
        let target_id = stable_class_id(source_name, &target.name);
        let target_lower = target.name.to_lowercase();
        output.push_str(&format!(
            "#[doc(hidden)] pub fn __rpp_is_exact_{}<T: RustppObject + ?Sized>(src: &T) -> bool {{ src.__rpp_type_desc().active_class == __RppClassId({target_id}) }}\n",
            target_lower
        ));
        output.push_str(&format!(
            "#[doc(hidden)] pub fn __rpp_is_{}<T: RustppObject + ?Sized>(src: &T) -> bool {{ src.__rpp_type_desc().find(__RppClassId({target_id})).is_some() }}\n",
            target_lower
        ));
        output.push_str(&format!(
            "trait __RppDynamicCastTo{} {{ type Output; fn __rpp_dynamic_cast(self) -> Self::Output; }}\n\
             fn __rpp_dynamic_as_{target_lower}<T: __RppDynamicCastTo{}>(src: T) -> T::Output {{ src.__rpp_dynamic_cast() }}\n\
             trait __RppDynamicIs{} {{ fn __rpp_dynamic_is(&self) -> bool; }}\n\
             fn __rpp_dynamic_is_{target_lower}<T: __RppDynamicIs{} + ?Sized>(src: &T) -> bool {{ src.__rpp_dynamic_is() }}\n",
            target.name, target.name, target.name, target.name
        ));
    }
    for source in &module.classes {
        for target in &module.classes {
            let source_view = format!("{}View", source.name);
            let target_view = format!("{}View", target.name);
            let target_lower = target.name.to_lowercase();
            let target_id = stable_class_id(source_name, &target.name);
            let stem = format!(
                "{}_to_{}",
                source.name.to_lowercase(),
                target.name.to_lowercase()
            );
            output.push_str(&format!(
                "#[doc(hidden)] pub fn __rpp_cast_ref_{stem}(src: &dyn {source_view}) -> Option<&dyn {target_view}> {{\n\
                 let entry = src.__rpp_type_desc().find(__RppClassId({target_id}))?;\n\
                 let root = src as *const dyn {source_view} as *const ();\n\
                 let mut out = std::mem::MaybeUninit::<*const dyn {target_view}>::uninit();\n\
                 // SAFETY [SC-CAST-THUNK]: the descriptor entry matches the complete root and initializes one borrowed target pointer whose lifetime is tied to `src`.\n\
                 unsafe {{ (entry.make_const)(root, out.as_mut_ptr().cast()); Some(&*out.assume_init()) }}\n\
                 }}\n"
            ));
            output.push_str(&format!(
                "#[doc(hidden)] pub fn __rpp_cast_mut_{stem}(src: &mut dyn {source_view}) -> Option<&mut dyn {target_view}> {{\n\
                 let make = src.__rpp_type_desc().find(__RppClassId({target_id}))?.make_mut;\n\
                 let root = src as *mut dyn {source_view} as *mut ();\n\
                 let mut out = std::mem::MaybeUninit::<*mut dyn {target_view}>::uninit();\n\
                 // SAFETY [SC-CAST-THUNK]: the unique complete-root borrow is preserved and the thunk initializes exactly one mutable target pointer.\n\
                 unsafe {{ make(root, out.as_mut_ptr().cast()); Some(&mut *out.assume_init()) }}\n\
                 }}\n"
            ));
            output.push_str(&format!(
                "#[doc(hidden)] pub fn __rpp_cast_box_{stem}(src: {}Box) -> Result<{}Box, {}Box> {{\n\
                 let make = match src.__rpp_type_desc().find(__RppClassId({target_id})) {{ Some(entry) => entry.make_mut, None => return Err(src) }};\n\
                 let raw = Box::into_raw(src); let root = raw as *mut ();\n\
                 let mut out = std::mem::MaybeUninit::<*mut dyn {target_view}>::uninit();\n\
                 // SAFETY [SC-OWNER-REBIND, SC-CAST-THUNK]: the thunk changes only view metadata; Box allocation, provenance, and sole destruction obligation are preserved.\n\
                 unsafe {{ make(root, out.as_mut_ptr().cast()); Ok(Box::from_raw(out.assume_init())) }}\n\
                 }}\n",
                source.name, target.name, source.name
            ));
            output.push_str(&format!(
                "#[doc(hidden)] pub fn __rpp_cast_rc_{stem}(src: {}Rc) -> Result<{}Rc, {}Rc> {{\n\
                 let make = match src.__rpp_type_desc().find(__RppClassId({target_id})) {{ Some(entry) => entry.make_const, None => return Err(src) }};\n\
                 let raw = std::rc::Rc::into_raw(src); let root = raw as *const ();\n\
                 let mut out = std::mem::MaybeUninit::<*const dyn {target_view}>::uninit();\n\
                 // SAFETY [SC-OWNER-REBIND, SC-CAST-THUNK]: the thunk changes only view metadata; the Rc allocation and exact strong/weak counts are preserved.\n\
                 unsafe {{ make(root, out.as_mut_ptr().cast()); Ok(std::rc::Rc::from_raw(out.assume_init())) }}\n\
                 }}\n",
                source.name, target.name, source.name
            ));
            output.push_str(&format!(
                "#[doc(hidden)] pub fn __rpp_cast_arc_{stem}(src: {}Arc) -> Result<{}Arc, {}Arc> {{\n\
                 let make = match src.__rpp_type_desc().find(__RppClassId({target_id})) {{ Some(entry) => entry.make_const, None => return Err(src) }};\n\
                 let raw = std::sync::Arc::into_raw(src); let root = raw as *const ();\n\
                 let mut out = std::mem::MaybeUninit::<*const dyn {target_view}>::uninit();\n\
                 // SAFETY [SC-OWNER-REBIND, SC-CAST-THUNK]: the thunk changes only view metadata; the Arc allocation and exact strong/weak counts are preserved.\n\
                 unsafe {{ make(root, out.as_mut_ptr().cast()); Ok(std::sync::Arc::from_raw(out.assume_init())) }}\n\
                 }}\n",
                source.name, target.name, source.name
            ));
            if class_conversion_is_public(module, source.id, target.id) {
                output.push_str(&format!(
                    "impl<'a> __RppDynamicCastTo{} for &'a dyn {source_view} {{\n\
                     type Output = Option<&'a dyn {target_view}>;\n\
                     fn __rpp_dynamic_cast(self) -> Self::Output {{ __rpp_cast_ref_{stem}(self) }}\n\
                     }}\n\
                     impl<'a> __RppDynamicCastTo{} for &'a mut dyn {source_view} {{\n\
                     type Output = Option<&'a mut dyn {target_view}>;\n\
                     fn __rpp_dynamic_cast(self) -> Self::Output {{ __rpp_cast_mut_{stem}(self) }}\n\
                     }}\n\
                     impl __RppDynamicCastTo{} for {}Box {{\n\
                     type Output = Result<{}Box, {}Box>;\n\
                     fn __rpp_dynamic_cast(self) -> Self::Output {{ __rpp_cast_box_{stem}(self) }}\n\
                     }}\n\
                     impl __RppDynamicCastTo{} for {}Rc {{\n\
                     type Output = Result<{}Rc, {}Rc>;\n\
                     fn __rpp_dynamic_cast(self) -> Self::Output {{ __rpp_cast_rc_{stem}(self) }}\n\
                     }}\n\
                     impl __RppDynamicCastTo{} for {}Arc {{\n\
                     type Output = Result<{}Arc, {}Arc>;\n\
                     fn __rpp_dynamic_cast(self) -> Self::Output {{ __rpp_cast_arc_{stem}(self) }}\n\
                     }}\n\
                     impl __RppDynamicIs{} for dyn {source_view} + '_ {{\n\
                     fn __rpp_dynamic_is(&self) -> bool {{ __rpp_is_{}(self) }}\n\
                     }}\n",
                    target.name,
                    target.name,
                    target.name,
                    source.name,
                    target.name,
                    source.name,
                    target.name,
                    source.name,
                    target.name,
                    source.name,
                    target.name,
                    source.name,
                    target.name,
                    source.name,
                    target.name,
                    target_lower
                ));
            }
        }
    }
}

fn class_conversion_is_public(
    module: &Module,
    source: crate::hir::ClassId,
    target: crate::hir::ClassId,
) -> bool {
    fn path(
        module: &Module,
        current: crate::hir::ClassId,
        target: crate::hir::ClassId,
        public: bool,
    ) -> Option<bool> {
        if current == target {
            return Some(public);
        }
        for base in &class_by_id(module, current).bases {
            if let Some(result) = path(
                module,
                base.class,
                target,
                public && base.visibility == crate::hir::BaseVisibility::Public,
            ) {
                return Some(result);
            }
        }
        None
    }
    path(module, source, target, true)
        .or_else(|| path(module, target, source, true))
        .unwrap_or(true)
}
