use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

fn main() -> ExitCode {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let grammar_path = root.join("grammar/rustpp.ungram");
    let grammar = match fs::read_to_string(&grammar_path) {
        Ok(grammar) => grammar,
        Err(error) => {
            eprintln!("failed to read {}: {error}", grammar_path.display());
            return ExitCode::FAILURE;
        }
    };
    let generated_nodes = [
        ("SourceFile", "SOURCE_FILE"),
        ("ValueClass", "VALUE_CLASS"),
        ("ClassDef", "CLASS_DEF"),
        ("FieldDef", "FIELD_DEF"),
        ("ConstructorDef", "CONSTRUCTOR_DEF"),
        ("Param", "PARAM"),
        ("NewExpr", "NEW_EXPR"),
        ("NewField", "NEW_FIELD"),
        ("TypeRef", "TYPE_REF"),
        ("Expr", "EXPR"),
        ("DestructorDef", "DESTRUCTOR_DEF"),
        ("InitBlock", "INIT_BLOCK"),
        ("DeinitBlock", "DEINIT_BLOCK"),
        ("DropBlock", "DROP_BLOCK"),
        ("Block", "BLOCK"),
        ("BaseList", "BASE_LIST"),
        ("BaseSpec", "BASE_SPEC"),
        ("BaseInit", "BASE_INIT"),
        ("MethodDef", "METHOD_DEF"),
        ("MethodSignature", "METHOD_SIGNATURE"),
        ("RustItem", "RUST_ITEM"),
        ("GenericParamList", "GENERIC_PARAM_LIST"),
    ];
    let mut missing = false;
    for (node, _) in generated_nodes {
        if !grammar
            .lines()
            .any(|line| line.starts_with(&format!("{node} =")))
        {
            eprintln!(
                "{} is missing required node `{node}`",
                grammar_path.display()
            );
            missing = true;
        }
    }
    if missing {
        return ExitCode::FAILURE;
    }
    let mut generated = String::from("// @generated by rustpp_ast_codegen; do not edit.\n");
    for (node, kind) in generated_nodes {
        generated.push_str(&format!("ast_node!({node}, {kind});\n"));
    }
    let output = root.join("crates/rustpp_compiler/src/ast/generated.rs");
    let check = env::args().any(|argument| argument == "--check");
    if check {
        if fs::read_to_string(&output).ok().as_deref() != Some(&generated) {
            eprintln!(
                "{} is stale; run cargo run -p rustpp_ast_codegen",
                output.display()
            );
            return ExitCode::FAILURE;
        }
    } else if let Err(error) = fs::write(&output, generated) {
        eprintln!("failed to write {}: {error}", output.display());
        return ExitCode::FAILURE;
    }
    ExitCode::SUCCESS
}
